### ISSUE TITLE
Add possibility to use noto-sans-emoji / different emoji-font

### ISSUE THREAD

**Issue by UnlimitedCookies** [eepp/jome#10]
Since the program is using Twemoji by default, I am very curious whether I can change the emoji that are shown in jome.

Or is this already possible, and I've overseen something?

**Comment by eepp** [comment]
It's not possible, or at least not easy.

Please read the jome [data generation process](https://github.com/eepp/jome/blob/master/gen-data/README.adoc).

jome doesn't use a font to show its emojis, but images.

Patches are always welcome if you want to contribute something. In that case, you can discuss your approach here.

**Comment by eepp** [comment]
Closing this.

Feel free to create a pull request should you implement something that's compatible with the jome license.
