### ISSUE TITLE
[Arch jome-git] `$ jome-ctl serverName` doesn't do anything

### ISSUE THREAD

**Issue by ToxicMushroom** [eepp/jome#17]
I run a server in a terminal like this:
`jome -s server`
and try to open an emoji picker using
`jome-ctl server`

Using just `jome` opens the window but this is slower ofcourse.
Perhaps this is a side effect from having had jome installed manually before.

**Comment by eepp** [comment]
The procedure you describe works perfectly for me.

When you run `jome -s server`, can you confirm that the command doesn't exit and you leave that terminal open?

Run exactly this and tell me if it works (brings up the jome window):

```
pkill -9 jome
rm -f /tmp/jomexyz
jome -s jomexyz &
sleep 1
jome-ctl jomexyz
```

What's your distribution, window manager, terminal emulator, and shell?

**Comment by ToxicMushroom** [comment]
I rebooted (again?) and can't reproduce it anymore

**Comment by eepp** [comment]
> I rebooted (again) and can't reproduce it anymore

Ok so what I think happens is that you have a hanging socket file in `/tmp`.

`jome -s` won't remove any file, but it doesn't warn if the file exists (which it should probably do) and just runs.

For the moment, make sure to always

1. Remove `/tmp/NAME`
2. Kill any running `jome -s NAME`

before running `jome -s NAME`. Also make sure `jome -s` continues to run in the background if you want `jome-ctl` to communicate with it.
