### ISSUE TITLE
Error installing from aur

### ISSUE THREAD

**Issue by kirk86** [eepp/jome#2]
Could you please have a look at this error 
![image](https://user-images.githubusercontent.com/2902390/68780445-383cea80-062e-11ea-8c86-4a847a38c86b.png)

Also, please update any python dependencies to python3, python2 is running out life soon, 2020 or 2022 I think.

**Comment by eepp** [comment]
I don't maintain the AUR package.

Maybe I should.

It looks like you're missing `python-yaml`, but I see it's a dependency, so I don't understand.

> Also, please update any python dependencies to python3, python2 is running out life soon, 2020 or 2022 I think.

Where do you see Python 2?

**Comment by eepp** [comment]
I _think_

**Comment by kirk86** [comment]
> It looks like you're missing `python-yaml`

Not so sure about that
```
 pacman -Ss python-yaml
community/python-yaml 5.1.2-1 [installed]
    Python bindings for YAML, using fast libYAML library

```


> Where do you see Python 2?

I think when it tries to install the dependencies like pycairo and some other python packages
I think all the dependencies are show [here](https://aur.archlinux.org/packages/jome-git/)

**Comment by eepp** [comment]
What does this say?

    python -c 'import yaml'

> I think when it tries to install the dependencies like pycairo and some other python packages I think all the dependencies are show here

They are all Python 3 dependencies. Anything which starts with `python-` on Arch Linux is Python 3.

**Comment by kirk86** [comment]
I did reinstall everything and got it working, but now I'm not sure how can I insert an emoji on a different app like an editor or something else?

**Comment by eepp** [comment]
> but now I'm not sure how can I insert an emoji on a different app like an editor or something else?

Did you read the README?

jome does not insert the emoji itself; it only picks an emoji and then prints it to the standard output. It can also execute a custom command.

To insert the selected emjoi, you need to combine jome with an existing tool that does that, for example xdotool.

Read the project's README to learn more. There are Bash script examples at the bottom to achieve what you want.

**Comment by kirk86** [comment]
> Did you read the README?

I did thanks, but I was trying to keep the number of installed third party apps to a minimum.

**Comment by eepp** [comment]
> I did thanks, but I was trying to keep the number of installed third party apps to a minimum.

xdotool is a very small package, don't worry.

> So there's no other way without xdotool I imagine.

Not with only jome at least.

**Comment by kirk86** [comment]
> xdotool is a very small package, don't worry.

I don't know if I made what I'm trying to clear. My scenario is the following I am supposedly on an editor and typing or on a webpage and typing now I want to use jome to pick an emoji and insert that in my editor or on the webpage or any other app that I'm currently using.

I have jome and xdotool installed but I can't find any example on how to achieve that and I suppose most usecases would fall under my scenario as well.

I've tried some existing scripts using xdotool which I've added into my bashrc but that opens jome with every terminal that I open and after selecting any emoji it adds it on the terminal.'
```
qt5ct: using qt5ct plugin
xdotool: Unknown command: 😆
Run 'xdotool help' if you want a command list
```
Neither of the above cases are my desired scenario. How can I just open jome upon request (e.g. Alt+F2 jome), pick an emoji and insert it into any third app?

**Comment by eepp** [comment]
Sorry if this is not clear.

Make your **Alt**+**F2** shortcut execute:

    jome -c 'xdotool type'

When you pick an emoji in jome, jome closes its main window, which brings back the typing focus to the previous window's text box, then waits a few ms to make sure it's done, then runs

    xdotool type <the emoji>

which inserts the emoji where your typing cursor was.
