### ISSUE TITLE
Making it more user friendly

### ISSUE THREAD

**Issue by PaulCombal** [eepp/jome#3]
Hello,
I just tried out jome, I must say it looks great!
I was looking for a newer replacement to this https://github.com/edam/emoji-keyboard, but jome looks more like a tool or a serverside thing.

I would love to have an icon for it in my taskbar and automatically type the emoji where my focus is.
I know I could do this myself but do you think this would be a great addition to have this option 'out of the box'?

Thanks

**Comment by eepp** [comment]
> I was looking for a newer replacement to this https://github.com/edam/emoji-keyboard, but jome looks more like a tool or a serverside thing.

What does "a serverside thing" even mean?

jome has a server, or daemon mode, in which the picker runs without any window being visible and you can make its window visible with another command (`jome-ctl`). This feature only exists to bring up the picker window instantly without having to wait for the application's startup time.

> 
> I would love to have an icon for it in my taskbar and automatically type the emoji where my focus is.
> I know I could do this myself but do you think this would be a great addition to have this option 'out of the box'?

You can use jome in many ways, but the classic use case is to:

1. Bring up the picker window with a dedicated keyboard shortcut.
2. Find and select an emoji (with the keyboard/mouse).
3. Insert the selected emoji where the focus was on the previous window.

To do this, bind a keyboard shortcut using whatever window manager you have to a script which launches `jome` and then makes it run `xdotool`, for example, to "type" the emoji once it hides the picker window.

See the README's "⌨️ the accepted emoji" section which contains some scripts to do this, for example:

```bash
#!/usr/bin/bash

emoji="$(jome)"

if [ $? -ne 0 ]; then
    exit 1
fi

xdotool type "$emoji"
```

I'll leave this issue open for you to reply.

**Comment by PaulCombal** [comment]
Sorry if I was unclear, what I meant is that, as is it looks like it's been conceived for automation, at least to me.

I guess regular desktop users don't want to create shell scripts to make it easy to use.
Can this simple script you wrote above be turned into a command-line option for example?

**Comment by eepp** [comment]
> Can this simple script you wrote above be turned into a command-line option for example?

In fact you can:

    $ jome -c 'xdotool type'

**Comment by PaulCombal** [comment]
Alright my bad. I'll probably make some kind of wrapper around it when I'll have some free time.
Thank you for your time, feel free to close the issue if there's nothing more to say!
