### ISSUE TITLE
Can't paste into firefox

### ISSUE THREAD

**Issue by MightyPork** [eepp/jome#6]
Hi, this is probably not something you can fix, but just in case you knew a workaround - the xdotool examples do not work for me with firefox, at all. Nothing is pasted.

I discovered it works great in
- Chrome, Sublime Text, Gnumeric, Libre Office, Gedit, gitk

doesn't work in:
- KWrite, Kate, Firefox, Konqueror

so maybe it works in GTK and Tcl/Tk apps and not in Qt apps? but I'm not sure. Thanks for any ideas

**Comment by eepp** [comment]
Hello! Thanks for using jome.

As you wrote, I'm not involved in `xdotool` in any way. I am aware that `xdotool` doesn't work all the time, and I couldn't say why honestly.

"Typing" into Chromium with `xdotool` used to just work, and then it stopped working for a few releases, and now it works again 😊. When it didn't work, I used `xdotool`, but also `xsel` to copy the emoji to the clipboard. So the usage sequence was:

1. Press keyboard shortcut to pop up jome.
2. Select emoji and then press Enter.
3. Press Ctrl+V to paste the emoji where the caret was.

Sometimes you play with delays and it can work too.

Closing this as it's not a jome bug.

Good luck with you emoji management!

**Comment by MightyPork** [comment]
Thanks, now I'm using this script. I hate it but it works so 🤷‍♂️ (inserted by jome 😂)

```bash
#!/usr/bin/bash

emoji="$(jome -n)"

if [ $? -ne 0 ]; then
   exit 1
fi

echo -n "$emoji" | xclip -selection clipboard
xdotool key --clearmodifiers shift+Insert
```

**Comment by eepp** [comment]
Wow, I never thought about this one. Great hack.

**Comment by Cruising0904** [comment]
> Thanks, now I'm using this script. I hate it but it works so man_shrugging (inserted by jome joy)
> 
> ```shell
> #!/usr/bin/bash
> 
> emoji="$(jome -n)"
> 
> if [ $? -ne 0 ]; then
>    exit 1
> fi
> 
> echo -n "$emoji" | xclip -selection clipboard
> xdotool key --clearmodifiers shift+Insert
> ```

in my wayland machine worked as expected with this script. I just used wl-copy instead of xclip, ydotool instead of xdotool. hope this helps somebody
